### ISSUE TITLE
Race condition in Oasis contract setup when checking confidentiality

### ISSUE THREAD

**Issue by peterjgilbert** [oasislabs/web3c.js#148]
https://github.com/oasislabs/web3c.js/blob/81432d9c076cc22b481b5d9242bf7d434bb6ff62/web3c/oasis.js#L122

**Comment by armaniferrante** [comment]
The fix here would be to make the Contract constructor asynchronous, since we can't know if a contract is confidential or not without first hitting the gateway.

@willscott what do you think? This is an unfortunate deviation from the web3.js api.

**Comment by willscott** [comment]
i'd really like to not have the contract constructor become asynchronous.

all the events on the contract are async, so we should have them queue up on knowing what type of contract it is

**Comment by armaniferrante** [comment]
@willscott excellent suggestion.

**Comment by willscott** [comment]
should be fixed by #149
