### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by armaniferrante** [oasislabs/web3c.js#153]

**Comment by willscott** [comment]
is #155 sufficient for this bug?

**Comment by armaniferrante** [comment]
It's sufficient for the example I've created. However, I'm waiting for sinchan to provide feedback as to whether its sufficient for his purposes, before cutting a new release.

Furthermore, we should I'd like to put the example into CI before closing the issue.

**Comment by ryscheng** [comment]
You should probably ping him to see if he's actually trying it or waiting
for a release

Cheers,
Ray

**Comment by armaniferrante** [comment]
I told him on Friday that I will not cut a release until he has confirmed the changes are sufficient.

**Comment by willscott** [comment]
We should open source https://github.com/oasislabs/react-native-web3c as the criteria for closing this issue.

Armani: I don't think it's an issue if we release it before we get confirmation from thinkable that all issues are resolved, and would advocate for doing that earlier.

**Comment by willscott** [comment]
@armaniferrante - any issues with open sourcing and calling this good pending feedback?

**Comment by armaniferrante** [comment]
No issues, though still waiting for feedback from sinchan. I'm happy to open source this.

**Comment by armaniferrante** [comment]
Open sourced. Closing.
