### ISSUE TITLE
Provide standalone (dist) version of web3c to that demo can be run independently.

### ISSUE THREAD

**Issue by marsrobertson** [oasislabs/web3c.js#94]
Here: https://github.com/oasislabs/web3c.js/blob/master/demo/index.html#L5

At first I `git clone` repository and jumped directly into the `demo` folder.

Only then I realised I need to `npm install` and `webpack`.

To have standalone version of `web3c` much faster to get started and observe the benefits (if any) of using it 😇

**Comment by willscott** [comment]
We have a link in our documentation, but could make it more prominent: The most recently published version of the library is available standalone at https://cdn.oasiscloud.io/web3c-latest/index.html

I'll take this issue as adding a `pre-publish` npm script to include the compilation output in the published NPM tarball.

**Comment by marsrobertson** [comment]
Ha! I see now, here it is: https://cdn.oasiscloud.io/web3c-latest/web3c.js

Basically this issue talks about being able to run `demo` without any external dependencies.

Good working demo and getting started = better adoption.

**Comment by willscott** [comment]
A standalone compiled version of the library is included in the v1.0.2 npm release.
